### ISSUE TITLE
Handler for doc$add('polygon')

### ISSUE THREAD

**Issue by dmi3kno** [coolbutuseless/minisvg#1]
As discussed in [this Twitter thread](https://twitter.com/dmi3k/status/1226237193880031232?s=20), could you please add a handler for polygons
![EQSArmmUwAAajuY](https://user-images.githubusercontent.com/13419011/74100213-8594ff00-4b2c-11ea-9bfe-993c126e5c4a.png)

**Comment by coolbutuseless** [comment]
As you mentioned, allowing data.frame or matrix input would also be convenient.

**Comment by coolbutuseless** [comment]
Fixed in 5725818fd

Can now specify (xs, ys) arguments in all places you can create polygons and polylines.

Also now expanded to accept 

* 'xs' as a data.frame with 'x' and 'y' columns  for the coordinates
* 'xs' as a matrix where first 2 columns are the x and y coordinates.

See vignette: https://coolbutuseless.github.io/package/minisvg/articles/specifying-coords-for-polygons-and-polylines.html
